name: "Woowtech HA Core 5"
description: "Woowtech Home Assistant Core instance 5"
version: "2.3.0"
slug: "woow_ha_core_5"
init: false
webui: "http://[HOST]:[PORT:8123]/"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8123/tcp: 8128
map:
  - "addon_config:rw"
